PREFIX ehri_units: <http://lod.ehri-project-test.eu/units/>
PREFIX rico: <https://www.ica.org/standards/RiC/ontology#>
PREFIX ehri: <http://lod.ehri-project-test.eu/ontology#>

CONSTRUCT {
  ?s ?p ?o .
} WHERE {
  {
    ?s ?p ?o .
    FILTER(?s = ehri_units:<$entityId>)
  }
  UNION
  {
    ?s ?p ?o ;
      a ?connectedClasses ;
      ?inverseProperty ?unit .
      VALUES ?connectedClasses { rico:Title rico:Activity rico:Identifier }
      FILTER(?unit = ehri_units:<$entityId>)
  }
  UNION
  {
    ?s ?p ?o .
    FILTER(?o = ehri_units:<$entityId>)
  }
}