PREFIX ehri_institutions: <http://lod.ehri-project-test.eu/institutions/>
PREFIX rico: <https://www.ica.org/standards/RiC/ontology#>
PREFIX ehri: <http://lod.ehri-project-test.eu/ontology#>

CONSTRUCT {
  ?s ?p ?o .
} WHERE {
  {
    ?s ?p ?o .
    FILTER(?s = ehri_institutions:<$entityId>)
  }
  UNION
  {
    ?s ?p ?o ;
      a ?connectedClasses ;
      ?inverseProperty ?institution .
    VALUES ?connectedClasses { ehri:InstitutionAddress rico:Coordinates ehri:ParallelAgentName ehri:AlternateAgentName rico:Mandate }
    FILTER(?institution = ehri_institutions:<$entityId>)
  }
  UNION
  {
    ?s ?p ?o ;
      a rico:Place ;
      rico:hasOrHadPhysicalLocation/rico:isOrWasPhysicalLocationOf ?institution .
    FILTER(?institution = ehri_institutions:<$entityId>)
  }
  UNION
  {
    ?s ?p ?o .
    VALUES ?p { rico:isOrWasLocationOfAgent }
    FILTER(?o = ehri_institutions:<$entityId>)
  }
}