PREFIX ehri_institutions: <http://lod.ehri-project-test.eu/institutions/>
PREFIX rico: <https://www.ica.org/standards/RiC/ontology#>
PREFIX ehri: <http://lod.ehri-project-test.eu/ontology#>

DELETE {
    ?s ?p ?o .
} WHERE {
    ?s ?p ?o .
    FILTER(?s = ehri_institutions:<$entityId>
        && ?p != rico:isOrWasHolderOf
        && ?p != ehri:isCopyOf
        && ?p != ehri:hasCopy)
}