PREFIX rico: <https://www.ica.org/standards/RiC/ontology#>
PREFIX ehri: <http://lod.ehri-project-test.eu/ontology#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX ehri_vocabs: <http://lod.ehri-project-test.eu/vocabularies/>

CONSTRUCT {
  ?s ?p ?o .
} WHERE {
  #{
    ?s ?p ?o .
    FILTER(?s = ehri_vocabs:<$entityId>
      && ?p != rico:isOrWasSubjectOf)
  #}
  #UNION
  #{
    #?s ?p ?o .
    # This is commented until the mapping rules cover this case
    #VALUES ?p { skos:hasTopConcept }
    #FILTER(?o = ehri_vocabs:<$entityId>)
  #}
}