PREFIX rico: <https://www.ica.org/standards/RiC/ontology#>
PREFIX ehri: <http://lod.ehri-project-test.eu/ontology#>
PREFIX ehri_vocabs: <http://lod.ehri-project-test.eu/vocabularies/>

CONSTRUCT {
  ?s ?p ?o .
} WHERE {
  {
    ?s ?p ?o .
    FILTER(?s = ehri_vocabs:<$entityId>)
  }
  UNION
  {
    ?s ?p ?o .
    FILTER(?o = ehri_vocabs:<$entityId>)
  }
  UNION
  {
    ?s ?p ?o ;
      a ?connectedClasses ;
      ?inverseProperty ?agent .
    VALUES ?connectedClasses { ehri:AlternateAgentName ehri:ParallelAgentName rico:LegalStatus rico:Activity rico:Mandate }
    FILTER(?agent = ehri_vocabs:<$entityId>)
  }
}